// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	NULL_DIALOGUE = 0,
	DEBUG_VENDOR = 1,
	My_Second_Dialogue = 2,
	Temp = 3,
}
